### ISSUE TITLE
Error in call to target 'main.metric_curve': KeyError('xxxxxx')

### ISSUE THREAD

**Issue by ShyWindddddd** [mantle2048/rlplot#3]
Error executing job with overrides: ['type=metric_curve']
Error in call to target 'main.metric_curve':
KeyError('InvertedDoublePendulum-v4')

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
make: *** [Makefile:5：all] 错误 1

in config.yaml
tasks:
  - Ant-v4
  - HalfCheetah-v4
  - Humanoid-v4
  - InvertedDoublePendulum-v4
  - Swimmer-v4

数据的格式也和作者相同，为什么这里还是报错呢

**Comment by mantle2048** [comment]
Hello，这是因为在示例中，对任务得分进行标准化的时候（参见[`random_score_norm_func`](https://github.com/mantle2048/rlplot/blob/master/main.py#L23))，只提供了Ant, HalfCheetah, Humanoid, Walker2d四个任务的随机得分，用于标准化。

你可以在该函数中添加你自己跑的Swimmer和InvertedDoublePendulum任务的随机策略的得分，例如：

```
    random_score = {
        'InvertedDoublePendulum-v4': x.xxxxxxxx,
        'Swimmer-v4':  xx.xxxxx
    }
```

或者，你也可以自己实现一个你想要的标准化函数。

**Comment by ShyWindddddd** [comment]
抱歉抱歉，是我的问题，看代码太粗心了。
想请教作者另一个问题，就是关于数据中“mean”的计算问题：
假如 Ant-v4 seed 0 的实验，跑到20w step 时对策略进行评估测试，测试20次，这时候最终记录的结果应该用IQM的结果还是mean呀，是不是也应该用IQM的结果作为 Ant-v4 seed 0 20w step的评估值，还是应该直接对20个数据求mean（那这样后面对不同种子的结果使用IQM的意义在哪里）
多有叨扰，已star~

**Comment by mantle2048** [comment]
Hi，抱歉回复晚了。
对于单次运行中的，时间步的性能记录，我认为你所说的用Mean和IQM都是可以的，关键在于每个 datapoint 都使用同一种标准即可。但是，Mean在单次运行中(似乎)是更流行的记录方式。

而在多次运行中，我们要根据多次运行的结果绘制性能阴影图，性能阴影图中的实线使用IQM指标绘制，可以很好地排除异常运行（过高或过低）对性能的干扰。

当然，如果你想绘制均值指标的curve，只需要把[`main/metric_curve`](https://github.com/mantle2048/rlplot/blob/master/main.py#L69)的参数修改为：
```
aggregate_name: str = 'MEAN'
```

**Comment by ShyWindddddd** [comment]
感谢回复！
